### ISSUE TITLE
ComputerCraft Turtles Cannot Break Protected Blocks on Server

### ISSUE THREAD

**Issue by Cringedo** [thexaero/open-parties-and-claims#635]
I am experiencing an issue where **ComputerCraft turtles** cannot mine blocks on my server when using the **Open Parties and Claims (OpenPAC)** mod. The turtles display the error **"Cannot Break Protected Blocks"**, even though I have configured the mod to allow them to bypass block protection.

The turtles work fine in singleplayer but fail to mine on the server, even in wilderness areas. I am the server owner and have full permissions.

# Steps to Reproduce:
1. Install the **OpenPAC** mod and **ComputerCraft** in a server environment (I'm using the Prominence 2 modpack).  
2. Add the following values to the PAC configuration:
   ```toml
   entitiesAllowedToGrief = ["computercraft:turtle", "computercraft:turtle_advanced", "computercraft:*turtle*", "[ComputerCraft]", "#computercraft:turtles"]
   staticFakePlayers = ["[IntegratedTunnels]", "dan200.computercraft.shared.turtle.core.TurtlePlayer", "[ComputerCraft]", "*"]
   staticFakePlayerClassExceptions = []
   ```
3. Restart the server and attempt to use a turtle to mine blocks in both wilderness and claimed areas.

# Expected Behavior:
The turtles should be able to mine blocks in both wilderness and claimed areas, as they are included in the `entitiesAllowedToGrief` and `staticFakePlayers` lists.

# Actual Behavior:
The turtles display the error **"Cannot Break Protected Blocks"** and cannot mine blocks in any area on the server.

# Environment:
- **Modpack:** Prominence 2  
- **Minecraft Version:** 1.20.1
- **OpenPAC Version:** 0.22.0
- **ComputerCraft Version:** 1.108.4
- **Server Type:** Fabric

# Additional Information:
- I have tested in both wilderness and claimed areas.  
- I have restarted the server after every configuration change.  
- No other mods (e.g., GriefPrevention, WorldGuard) are installed that should interfere with block protection.  
- The turtles work fine in singleplayer with the same configuration.

# Request:
Could you please confirm if there are additional settings or steps required to allow ComputerCraft turtles to bypass block protection? If this is a bug, I’d appreciate any guidance or fixes.
